name: easy_app_cli
description: A Good Command Line Application created by Easy Apps
version: 1.0.0+1-dev.01
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.10
  build_version: ^2.1.1
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

executables:
  easy_app:
    
dependencies: 
  args: ^2.3.0
  cli_dialog: ^0.5.0
  mason: ^0.1.0-dev.20
  mason_logger: ^0.1.0-dev.8
  process_run: ^0.12.3+2
  universal_io: ^2.0.4
